=== podaac/cloud-notification-message-schema/cumulus_sns_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "file": {
      "type": "object",
      "properties": {
        "type": {
          "description": "The type of file. science files (netcdf, HDF, binary) should use the 'data' type. More can be added if need and consensus demand.",
          "type": "string",
          "enum": [
            "data",
            "browse",
            "metadata",
            "ancillary",
            "linkage"
          ]
        },
        "subtype": {
          "description": "An optional, specific implmentation of the file::type. e.g. NetCDF for a file of type 'data'",
          "type": "string"
        },
        "uri": {
          "description": "the URI of the file (s3://...)",
          "type": "string"
        },
        "name": {
          "description": "The human readable filename that this file represents. ",
          "type": "string"
        },
        "checksumType": {
          "description  ": "Type of the checksum (e.g. md5). Optional. If no checksumType is defined for a file, it is assumed to be md5",
          "type": "string",
          "enum": [
            "SHA512",
            "SHA256",
            "SHA2",
            "SHA1",
            "md5"
          ]
        },
        "checksum": {
          "description": "Checksum of the file.",
          "type": "string"
        },
        "size": {
          "description": "Size, in bytes, of the file.",
          "type": "number"
        }
      },
      "required": [
        "type",
        "uri",
        "size",
        "name"
      ]
    },
    "filegroup": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "string id of the filegroup by which all files are associated."
        },
        "files": {
          "description": "array of files that make up this product",
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        }
      },
      "required": [
        "id",
        "files"
      ]
    },
    "collection": {
      "description": "The collection short name and version.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "collection short name."
        },
        "version": {
          "type": "string",
          "description": "collection version."
        }
      },
      "required": [
        "name",
        "version"
      ]
    }
  },
  "title": "Cloud Notification Message (cnm) 1.2 ",
  "description": "A message format to trigger or respond to processing. Version 1.2",
  "type": "object",
  "properties": {
    "version": {
      "description": "The CNM Version used. e.g. '1.3'",
      "type": "string",
      "enum": [
        "1.0",
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.4.1",
        "1.5",
        "1.5.1",
        "1.6.0",
        "1.6.1-alpha.0"
      ]
    },
    "receivedTime": {
      "description": "Time message was received by the ingest system",
      "type": "string",
      "format": "date-time"
    },
    "processCompleteTime": {
      "description": "The time processing completed by the receiving entity.",
      "type": "string",
      "format": "date-time"
    },
    "submissionTime": {
      "description": "The time the message was created (and presumably sent) to the publication mechanism.",
      "type": "string",
      "format": "date-time"
    },
    "identifier": {
      "description": "Unique identifier for the message as a whole. It is the senders responsibility to ensure uniqueness. This identifier can be used in response messages to provide tracability.",
      "type": "string"
    },
    "collection": {
      "description": "The collection to which these granules will belong.",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/collection"
        }
      ]
    },
    "provider": {
      "description": "the name of the provider (e.g. SIP, SDS, etc. ) producing these files.",
      "type": "string"
    },
    "trace": {
      "description": "Information on the message or who is sending it.",
      "type": "string"
    },
    "response": {
      "description": "The response message type sent. Can be a success message or error message. Akin to both the PAN and PDRD",
      "type": "object",
      "properties": {
        "status": {
          "description": "Successful or error.",
          "type": "string",
          "enum": [
            "SUCCESS",
            "FAILURE"
          ]
        },
        "ingestionMetadata": {
          "description": "Object defining ingestion metadata, like CMR Concept IDs, URLS, etc",
          "type": "object",
          "properties": {
            "catalogId": {
              "description": "Identifier for catalog",
              "type": "string"
            },
            "catalogUrl": {
              "description": "URL of catalog entry",
              "type": "string"
            }
          }
        },
        "errorCode": {
          "description": "Error message. Success messages can be ignored.",
          "type": "string",
          "enum": [
            "VALIDATION_ERROR",
            "PROCESSING_ERROR",
            "TRANSFER_ERROR"
          ]
        },
        "errorMessage": {
          "description": "The message error for the failure that occured.",
          "type": "string"
        }
      },
      "required": [
        "status"
      ]
    },
    "product": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Identifier/name of the product",
          "type": "string"
        },
        "producerGranuleId": {
          "description": "Optional provider-assigned granule identifier for this product",
          "type": "string"
        },
        "dataVersion": {
          "description": "Version of this product",
          "type": "string"
        },
        "dataProcessingType": {
          "description": "The type of data processing stream that generated the product",
          "type": "string",
          "enum": [
            "forward",
            "reprocessing"
          ]
        },
        "files": {
          "description": "array of files that make up this product",
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        },
        "filegroups": {
          "description": "array of filegroups that make up this product",
          "type": "array",
          "items": {
            "$ref": "#/definitions/filegroup"
          }
        }
      },
      "oneOf": [
        {
          "required": [
            "name",
            "files"
          ]
        },
        {
          "required": [
            "name",
            "filegroups"
          ]
        }
      ]
    }
  },
  "oneOf": [
    {
      "required": [
        "version",
        "submissionTime",
        "collection",
        "identifier",
        "product"
      ],
      "not": {
        "required": [
          "response"
        ]
      }
    },
    {
      "required": [
        "version",
        "receivedTime",
        "processCompleteTime",
        "submissionTime",
        "identifier",
        "collection",
        "response"
      ]
    }
  ]
}

=== podaac/cloud-notification-message-schema/samples/cumulus_sns_v1.1_dataVersions.json
{
  "version":"1.1",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "submissionTime":"2017-09-30T03:42:29.791198Z",
  "identifier": "1234-abcd-efg0-9876",
  "product":
    {
      "name": "sampleGranuleName001",
      "filegroups" : [{
        "id" : "filgroup1",
        "files": [
          {
            "type": "data",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.nc",
            "name":"production_file.nc",
            "checksumType": "md5",
            "checksum": "4241jafkjaj14jasjf",
            "size": 123456
          },
          {
            "type": "browse",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.png",
            "name":"production_file.png",
            "checksumType": "md5",
            "checksum": "addjd872342bfbf",
            "size": 12345
          }
        ]
      },
      {
        "id" : "filgroup2",
        "files": [
          {
            "type": "data",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.nc",
            "name":"production_file.nc",
            "checksumType": "md5",
            "checksum": "4241jafkjaj14jasjf",
            "size": 123456
          },
          {
            "type": "browse",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.png",
            "name":"production_file.png",
            "checksumType": "md5",
            "checksum": "addjd872342bfbf",
            "size": 12345
          }
        ]
      }]
   }
}

=== podaac/cloud-notification-message-schema/samples/cumulus_sns_v1.6_notification.json
{
  "version":"1.6.0",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "submissionTime":"2020-07-28T04:48:22.405460Z",
  "identifier": "1234-abcd-efg0-9876",
  "product":
    {
      "name": "sampleGranuleName001",
      "dataVersion": "001",
      "dataProcessingType": "forward",
      "files": [
        {
          "type": "data",
          "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.nc",
          "name":"production_file.nc",
          "size": 123456
        },
        {
          "type": "browse",
          "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.png",
          "name":"production_file.png",
          "checksum":"12312312312313",
          "checksumType":"SHA512",
          "size": 12345
        }
      ]
    }
}

=== podaac/cloud-notification-message-schema/samples/cumulus_sns_v1.2_response_success_cmr_id.json
{
  "version": "1.2",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "processCompleteTime":"2017-09-30T03:45:29.791198Z",
  "receivedTime":"2017-09-30T03:42:31.634552Z",
  "submissionTime":"2017-09-30T03:42:29.791198Z",
  "identifier": "1234-abcd-efg0-9876",
  "response": {
    "status":"SUCCESS",
    "ingestionMetadata":{
      "catalogId":"G1226018937-POCUMULUS",
      "catalogUrl":"https://cmr.uat.earthdata.nasa.gov:443/search/concepts/G1226018937-POCUMULUS/1"
    }
  }
}

=== podaac/cloud-notification-message-schema/samples/cumulus_sns_v1.5_notification.json
{
  "version": "1.5",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "processCompleteTime":"2017-09-30T03:45:29.791198Z",
  "receivedTime":"2017-09-30T03:42:31.634552Z",
  "submissionTime":"2017-09-30T03:42:29.791198Z",
  "identifier": "1234-abcd-efg0-9876",
  "response": {
    "status":"SUCCESS"
  }
}

=== podaac/cloud-notification-message-schema/samples/cumulus_sns_v1.5_response_success_product.json
{
  "version": "1.5",
  "provider": "PODAAC",
  "submissionTime": "2020-11-06T17:17:29.339531Z",
  "collection": "MODIS_A-JPL-L2P-v2019.0",
  "identifier": "f2d5aca2-2053-11eb-8e6f-acde48001122",
  "trace": "NCMODIS_A-JPL-L2P-v2019.01",
  "product": {
    "dataVersion": "2019.0",
    "files": [
      {
        "type": "data",
        "name": "20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc",
        "uri": "https://es3uvapgyg.execute-api.us-west-2.amazonaws.com:9000/DEV/podaac-sndbx-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc",
        "checksumType": "md5",
        "checksum": "aa5204f125ae83847b3b80fa2e571b00",
        "size": 18232098
      },
      {
        "type": "metadata",
        "name": "20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc.md5",
        "uri": "https://es3uvapgyg.execute-api.us-west-2.amazonaws.com:9000/DEV/podaac-sndbx-cumulus-public/MODIS_A-JPL-L2P-v2019.0/20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc.md5",
        "size": 98
      },
      {
        "type": "metadata",
        "name": "20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.cmr.json",
        "uri": "https://es3uvapgyg.execute-api.us-west-2.amazonaws.com:9000/DEV/podaac-sndbx-cumulus-public/MODIS_A-JPL-L2P-v2019.0/20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.cmr.json",
        "size": 1633
      }
    ],
    "name": "20200101000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0"
  },
  "receivedTime": "2020-11-06T17:18:49.506Z",
  "response": {
    "status": "SUCCESS",
    "ingestionMetadata": {
      "catalogId": "G1238611022-POCUMULUS",
      "catalogUrl": "https://cmr.uat.earthdata.nasa.gov/search/granules.json?concept_id=G1238611022-POCUMULUS"
    }
  },
  "processCompleteTime": "2020-11-06T17:21:13.523Z"
}
